### ISSUE TITLE
Removal of dunfell support from master

### ISSUE THREAD

**Issue by kevswims** [IntelRealSense/meta-intel-realsense#28]
Why was dunfell support removed from the master branch? 

Dunfell is an LTS release and being able to still use the latest librealsense releases on it is very important to us. Unless there has been a breaking change that prevents dunfell from being supported can the removal of dunfell as a compatible layer be reverted?

If librealsense was stable and did not require updates to get our system working this would be OK but we are unable to even run the D435 camera at all the resolutions on our platform without the latest librealsense and FW.

**Comment by srware** [comment]
@kevswims the standard Yocto layer maintenance approach usually means that the master branch is a prep zone for the next stable release so anything relating to dunfell such as kernel patches etc... will be surplus when it comes to merging for the hardknott release.

That said there are always two trains of thought amongst users, those who don't want the library versions to change in a stable branch because it breaks things and those who want cutting edge in all branches. It's generally frowned upon to update beyond point releases of any given package version in a stable branch so in this instance adding dunfell back to master would be preferred although I wouldn't be able to guarantee dunfell support if something in a newer branch mandated a breaking change.

In an ideal world the librealsense team would maintain an LTS release say once a year which got support for new hardware and security patches without breaking the API. We could then track this release and update the Yocto LTS branch in situ.

Let me take a look at adding dunfell back to master and see how this goes for the remainder of the dunfell support cycle.
